language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15

jdk:
  - oraclejdk8

before_script:
  - echo no | android create avd --force -n test -t android-15 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "DbzTwxqv4Vw8tf3BDqvaB5ZdqRxLuzdVcyFJF6s0lsHhHrJHRiqJHY+fN/OJtnMe1pAIYWj6gglFxnEBQ2rAFet/PzLQHUtoMTJh/z0AJBSMiEKOlDO6QeWDIUCRYGxdvMD/udwWnNccyXqKNtSwMLHUNaQkLNQ5lOdPi81lVFWmoI7DG+HTJqetu2HzxzVQSteHVEM5uKh5tVuKCizAQB4gxzxNpph7LlEuONvpg2+owpqC5MVBQIkoEItb3KDaBIBO2opDdR6hKVz9tQczElpshgXzxGYUylINCjb1pM//AjaWt30UfeqUQfsyuCnPF3tYJgUmPfng1o8o7XyVxDq7DNJXIAFSpmBOCUh1XjYyzn0u1/0bkjLOqzpMQcW5e1YfJsF+P53QSQA4xjpPluvddxTGwzgNgQ66EBWB7Ty1duseQPHpfj9s+wgtTX9edP07RSVcBBl35iiVHen5FU4A2fh9NvH/7mUnp4ZJkwIhuGjmuVY7PImrIyALa5UZ7i+SoNajPo7M+hZKWPowz6TVxdIDXbfYSv7JmJtFaiyRlDvDsTaPy1ujnpmwdsGBkaHfH5O7x7XWvMBGjHdPLoCKgMn8ebHuUHLqyK3oYaEP2ffoDzGnc1FYKJRSK8gPYhX2efr8ZbetQsIUvfIbzbYlRXs1JQfhFjXTKkLO5N4="
    - secure: "13a02et8CmG3CGCLm+AvqmzQXvTkwDFh3WMsNBLrg3wIDaJG2bYSYeSSkk/qir/f3kPoE9i1NdU0Jt8kxX+FZCU1osj5XlFwDY/pS61z3raF5rErcFFDAiIH05N6bE+J7BMnrL773menbZGLD/K4JuLwNnKewM8qXIWuZIwmbw9+DxBKxK0A8rBGafjLXw/98goCXpZa5t77FJMr+n/AOQHByga2dULYo1A9xVUMIcVJ0U54Gv12VANCXNIEy4bieYggKzFBYZbnjm2EfEygpzg8aiwqpLlKHi1Wx38pSmp0aPCI28OMPAWDyX/TfrP8DSq+L+oG//LFhC1scF+nYZFA9QHuENvTgKG3eqjh6tsKpocgGUAiK3pLBQMcNtE7/vLMry1NHE7obSM7lgf8CCw/GJcyMQUAnyF1P8LPjcz9sce7dY8lIyv49SZVF8pEvHniBjf7YIgzOMXCMuMzeJVp75eIbLTBxIfkiK7FmCERFpyXzmSDiI7/ovCEdbugHRbnVB+8pdBXJFH6FlFngyeJhwugccFd3kOlagDSONuvwAjo4XxqP2nTTp4tiwWTWnNWaQQYzwVeo+hR2HZdlkE9u8YgNBvMKPU1Hc1+jMXoWl1Sp+n9rAQ+F1l7EqFQqMuu4+ZvmT8KpREW+nPm2+nNkj0TUoorxFT1MrxHfPs="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle

after_failure:
    - find . -name "lint-results-*.xml" | xargs cat

