name: upgrade

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./update.sh

      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: Bump ThreeTenBP dependency and embedded TZDB.
          title: Upgrade ThreeTenBP
          body: Bump dependency and embedded timezone database.
          branch: upgrade
          delete-branch: true
